server:
  port: 8763
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #指定注册中心地址
spring:
  application:
    name: service-hi #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name



